name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Deploying index.html..."
            # Backup existing index.html
            if [ -f /var/www/html/index.html ]; then
              mv /var/www/html/index.html /var/www/html/index.html.bak
            fi
          # Upload index.html from GitHub runner
          local_path: index.html
          remote_path: /var/www/html/index.html

      - name: Restart Apache
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: sudo systemctl restart apache2
