name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to EC2 (rsync)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub || true
          # add known_hosts (optional if you trust ssh-keyscan)
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        env:
          EC2_IP: ${{ secrets.EC2_IP }}

      - name: Copy files to EC2 (rsync)
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes" \
            ./ ubuntu@${{ secrets.EC2_IP }}:/var/www/html/
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_USER: ${{ secrets.EC2_USER }}

      - name: Restart nginx on EC2 (optional)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
