name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy code to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Deploying code..."
          cd /var/www/html
          # Backup existing index.html
          if [ -f index.html ]; then mv index.html index.html.bak; fi
          # Copy new file from GitHub runner
          echo "${{ steps.checkout.outputs.path }}/index.html"  # Debug
          # Using scp-like approach
          cat <<'EOF' > index.html
$(cat index.html)
EOF
          sudo systemctl restart apache2
