name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to EC2
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem index.html $EC2_USER@$EC2_IP:/var/www/html/index.html
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
          EC2_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Apache
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: sudo systemctl restart apache2
